name: CI ubicloud test
on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubicloud-standard-8-arm
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ENABLE_FDKAAC=1
